version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
  backend:
    build: ./scarlet-api/
    ports:
      - "6200:6200"
    volumes:
      - ./scarlet-api:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: scarlet-app/
    ports:
      - "3000:3000"
    volumes:
      - ./scarlet-app:/usr/src/app
    depends_on:
    - backend
