version: '2.1'

services:
  scarlet-api:
    image: scarlet-api
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 6200:6200
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 server.js